name: Deploy Application

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed
  

jobs:
  deploy:

    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-skip-session-tagging: true


    - name: Deploy AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name STUDENTIFY_CHRSTIAN \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name STUDENTIFY_CHRSTIAN \
          --github-location "repository=${{ github.repository }},commitId=${{ github.sha }}" \
          --region us-east-1 \
          --description "DEPLOY STUDENTIFY CHRISTIAN"
